/**
 * @Project       NgSSR Todo App
 * @BD_ID         TODO-001
 * @Description   HTTP API service for Todo CRUD operations
 * @Author        developer
 * @CreatedDate   2026-01-09
 * @Updater       developer
 * @LastUpdated   2026-01-10
 */

import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Observable, throwError } from "rxjs";
import { Todo } from "../models";
import { environment } from "../../../../environments/environment";
import {
  isValidId,
  isValidTitle,
  sanitizeString,
  TODO_ERROR_MESSAGES,
} from "../../../shared";

@Injectable({
  providedIn: "root",
})
export class TodoApiService {
  private readonly baseUrl = `${environment.apiBaseUrl}/todos`;

  constructor(private http: HttpClient) {}

  /**
   * Get all todos from the API
   * @returns Observable<Todo[]>
   */
  getTodos(): Observable<Todo[]> {
    return this.http.get<Todo[]>(this.baseUrl);
  }

  /**
   * Add a new todo to the API
   * @param todo - Todo object without id (id will be generated by json-server)
   * @returns Observable<Todo> or error if validation fails
   */
  addTodo(todo: Omit<Todo, "id">): Observable<Todo> {
    // Validate and sanitize title
    if (!isValidTitle(todo.title)) {
      return throwError(() => new Error(TODO_ERROR_MESSAGES.INVALID_TITLE));
    }

    const sanitizedTodo = {
      ...todo,
      title: sanitizeString(todo.title),
    };

    return this.http.post<Todo>(this.baseUrl, sanitizedTodo);
  }

  /**
   * Update an existing todo
   * @param id - Todo id to update
   * @param updates - Partial todo object with fields to update
   * @returns Observable<Todo> or error if validation fails
   */
  updateTodo(id: string, updates: Partial<Todo>): Observable<Todo> {
    // Validate id format
    if (!isValidId(id)) {
      return throwError(() => new Error(TODO_ERROR_MESSAGES.INVALID_ID));
    }

    // Validate and sanitize title if provided
    const sanitizedUpdates: Partial<Todo> = { ...updates };
    if (updates.title !== undefined) {
      if (!isValidTitle(updates.title)) {
        return throwError(() => new Error(TODO_ERROR_MESSAGES.INVALID_TITLE));
      }
      sanitizedUpdates.title = sanitizeString(updates.title);
    }

    return this.http.patch<Todo>(`${this.baseUrl}/${id}`, sanitizedUpdates);
  }

  /**
   * Delete a todo by id
   * @param id - Todo id to delete
   * @returns Observable<void> or error if validation fails
   */
  deleteTodo(id: string): Observable<void> {
    // Validate id format
    if (!isValidId(id)) {
      return throwError(() => new Error(TODO_ERROR_MESSAGES.INVALID_ID));
    }

    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }
}
