/**
 * @Project       NgSSR Todo App
 * @BD_ID         TODO-001
 * @Description   HTTP API service for Todo CRUD operations
 * @Author        developer
 * @CreatedDate   2026-01-09
 * @Updater       developer
 * @LastUpdated   2026-01-09
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Todo } from '../models/todo.model';

@Injectable({
  providedIn: 'root',
})
export class TodoApiService {
  private baseUrl = 'http://localhost:3000/todos';

  constructor(private http: HttpClient) {}

  /**
   * Get all todos from the API
   * @returns Observable<Todo[]>
   */
  getTodos(): Observable<Todo[]> {
    return this.http.get<Todo[]>(this.baseUrl);
  }

  /**
   * Add a new todo to the API
   * @param todo - Todo object without id (id will be generated by json-server)
   * @returns Observable<Todo>
   */
  addTodo(todo: Omit<Todo, 'id'>): Observable<Todo> {
    return this.http.post<Todo>(this.baseUrl, todo);
  }

  /**
   * Update an existing todo
   * @param id - Todo id to update
   * @param updates - Partial todo object with fields to update
   * @returns Observable<Todo>
   */
  updateTodo(id: string, updates: Partial<Todo>): Observable<Todo> {
    return this.http.patch<Todo>(`${this.baseUrl}/${id}`, updates);
  }

  /**
   * Delete a todo by id
   * @param id - Todo id to delete
   * @returns Observable<void>
   */
  deleteTodo(id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }
}
